server:
  port: 8080

spring:
  datasource:
     url: jdbc:mysql://101.132.111.57:3306/dianping?useUnicode=true&characterEncoding=utf8
     username: root
     password: Xu.123456
     driver-class-name: com.mysql.jdbc.Driver
  application:
    name: dev

logging:
  path: /logs/dev/




